### ISSUE TITLE
Unable to connect to mongodb

### ISSUE THREAD

**Issue by bigfootdeveloper** [trizin/Telegram-Airdrop-Bot#10]
Y follow the instructions of the README but when I look at the log of the container, it can not connect to mongodb container.

```
# docker container logs d1eee0d92fde 
Traceback (most recent call last):
  File "bot.py", line 65, in <module>
    users.create_index([('ref', pymongo.TEXT)], name='search_index', default_language='english')
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 2059, in create_index
    return self.__create_indexes([index], session, **cmd_options)[0]
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 1919, in __create_indexes
    with self._socket_for_writes(session) as sock_info:
  File "/usr/local/lib/python3.7/site-packages/pymongo/collection.py", line 198, in _socket_for_writes
    return self.__database.client._socket_for_writes(session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1293, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 243, in select_server
    address))
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 200, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python3.7/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: mongodb:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 616f3d6ec9f251e78b749b6e, topology_type: Single, servers: [<ServerDescription ('mongodb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongodb:27017: [Errno 111] Connection refused')>]>
```

I tried too to use mongo 4.4.10 too, but same result.  If I open a bash shell in the mongodb container and execute db.auth('root','secret_password') it didn't find the user.

What am I doing wrong?

Thanks

**Comment by bigfootdeveloper** [comment]
It was shorewall firewall.
