### ISSUE TITLE
Problem to start

### ISSUE THREAD

**Issue by Assisf** [trizin/Telegram-Airdrop-Bot#13]
I started docker-compose up -d and after this terminal tells me that's okay.

But when i'm type /start on telegramchatbot this error occurs

`bot_service_1  | 2021-11-12 12:10:03,705 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.

bot_service_1  | Traceback (most recent call last):

bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update

bot_service_1  |     handler.handle_update(update, self, check, context)

bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update

bot_service_1  |     new_state = handler.handle_update(update, dispatcher, check_result, context)

bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update

bot_service_1  |     return self.callback(update, context)

bot_service_1  |   File "bot.py", line 187, in checkCaptcha

bot_service_1  |     if CAPTCHA_DATA[user.id] != text:

bot_service_1  | KeyError: 960534555`

**Comment by Skandesh** [comment]
I'm getting this same error, did you find any workaround for this? @Assisf

**Comment by Skandesh** [comment]
> I'm getting this same error, did you find any workaround for this? @Assisf

Update - I was using `admin` as my telegram username, you need to change it to your telegram username.
