### ISSUE TITLE
Getting a parse issue

### ISSUE THREAD

**Issue by hodlape** [trizin/Telegram-Airdrop-Bot#21]
bot works until you hit submit details I think it is to do with the python_telegram_bot==13.1 requirement being out dated? tried to update to the latest but doesnt work at all

error log 

bot.py:219: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere

**Comment by Skandesh** [comment]
Hey @hodlape  can you post the full error message here, i'm getting a similar kinda issue

**Comment by elusiee** [comment]
This is the same issue I'm having when I click submit details: 

Error Log:

2023-06-24 02:52:54,101 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/home/alonsome/Projects/Python/CyberVerse/utils/handlers.py", line 76, in follow_telegram
    update.message.reply_text(
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/message.py", line 603, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/home/alonsome/.local/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/bot.py", line 135, in decorator
    result = func(*args, **kwargs)
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/bot.py", line 458, in send_message
    return self._message(  # type: ignore[return-value]
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/bot.py", line 281, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/bot.py", line 245, in _post
    return self.request.post(f'{self.base_url}/{endpoint}', data=data, timeout=timeout)
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 349, in post
    result = self._request_wrapper(
  File "/home/alonsome/.local/lib/python3.10/site-packages/telegram/utils/request.py", line 272, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: can't find end of the entity starting at byte offset 66

**Comment by elusiee** [comment]
> bot works until you hit submit details I think it is to do with the python_telegram_bot==13.1 requirement being out dated? tried to update to the latest but doesnt work at all
> 
> error log
> 
> bot.py:219: DeprecationWarning: count is deprecated. Use estimated_document_count or count_documents instead. Please note that $where must be replaced by $expr, $near must be replaced by $geoWithin with $center, and $nearSphere must be replaced by $geoWithin with $centerSphere

How did you solve it bro, I'm having quite the same issue.
