### ISSUE TITLE
Warning service bot_servis

### ISSUE THREAD

**Issue by MyDemir** [trizin/Telegram-Airdrop-Bot#30]
.

**Comment by MyDemir** [comment]
I have overcome other problems by editing the request file, but when I look at the logs, I encounter an error. So I'm having trouble communicating with telegram. (There's no such thing as a "telegram" library in particular.)

root@A2:~# docker container logs c69
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from utils.handlers import *
  File "/app/utils/handlers.py", line 8, in <module>
    from telegram.ext import (
ImportError: cannot import name 'Filters' from 'telegram.ext' (/usr/local/lib/python3.7/site-packages/telegram/ext/__init__.py)

**Comment by MyDemir** [comment]
`.
root@A2:~# docker container logs 518
2023-01-16 14:23:35,455 - apscheduler.scheduler - INFO - Scheduler started
2023-01-16 14:35:10,124 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/app/utils/handlers.py", line 253, in start
    if refferal != "" and refferal != user.id and "ref" not in getUserInfo(user.id):
TypeError: argument of type 'bool' is not iterable
2023-01-16 14:35:19,045 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/app/utils/handlers.py", line 253, in start
    if refferal != "" and refferal != user.id and "ref" not in getUserInfo(user.id):
TypeError: argument of type 'bool' is not iterable
2023-01-16 14:35:50,504 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/app/utils/handlers.py", line 253, in start
    if refferal != "" and refferal != user.id and "ref" not in getUserInfo(user.id):
TypeError: argument of type 'bool' is not iterable
2023-01-16 14:36:35,997 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/app/utils/handlers.py", line 253, in start
    if refferal != "" and refferal != user.id and "ref" not in getUserInfo(user.id):
TypeError: argument of type 'bool' is not iterable
2023-01-16 14:39:19,066 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/app/utils/handlers.py", line 253, in start
    if refferal != "" and refferal != user.id and "ref" not in getUserInfo(user.id):
TypeError: argument of type 'bool' is not iterable
2023-01-16 14:40:09,836 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 432, in process_update
    handler.handle_update(update, self, check, context)
  File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line 517, in handle_update
    new_state = handler.handle_update(update, dispatcher, check_result, context)  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 156, in handle_update
    return self.callback(update, context)
  File "/app/utils/handlers.py", line 253, in start
    if refferal != "" and refferal != user.id and "ref" not in getUserInfo(user.id):
TypeError: argument of type 'bool' is not iterable
2023-01-16 15:09:36,293 - telegram.ext.updater - INFO - Received signal 15 (SIGTERM), stopping...
2023-01-16 15:09:36,293 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-01-16 15:10:47,635 - apscheduler.scheduler - INFO - Scheduler started
2023-01-16 16:07:37,441 - telegram.ext.updater - INFO - Received signal 15 (SIGTERM), stopping...
2023-01-16 16:07:37,442 - apscheduler.scheduler - INFO - Scheduler has been shut down
2023-01-16 16:09:52,728 - apscheduler.scheduler - INFO - Scheduler started
root@A2:~# ``
