### ISSUE TITLE
Can't install with docker on Ubuntu 20

### ISSUE THREAD

**Issue by Ch4ttY** [trizin/Telegram-Airdrop-Bot#6]
Hey,  I got an issue with MongoDB installing on Ubuntu 20. 
"mongodb 5.0+ requires a cpu with avx support"

Not many VPS support that.

bot_service_1  | 2021-10-07 22:52:11,195 - apscheduler.scheduler - INFO - Scheduler started
bot_service_1  | 2021-10-07 22:52:45,448 - telegram.ext.dispatcher - ERROR - No error handlers are registe                                         red, logging exception.
bot_service_1  | Traceback (most recent call last):
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in                                          process_update
bot_service_1  |     handler.handle_update(update, self, check, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line                                          626, in handle_update
bot_service_1  |     new_state = handler.handle_update(update, dispatcher, check_result, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in han                                         dle_update
bot_service_1  |     return self.callback(update, context)
bot_service_1  |   File "bot.py", line 187, in checkCaptcha
bot_service_1  |     if CAPTCHA_DATA[user.id] != text:
bot_service_1  | KeyError: 65219073
bot_service_1  | bot.py:476: DeprecationWarning: count is deprecated. Use Collection.count_documents inste                                         ad.
bot_service_1  |   refes = users.find({"ref": {"$ne": False}}).count()
bot_service_1  | bot.py:482: DeprecationWarning: count is deprecated. Use Collection.count_documents inste                                         ad.
bot_service_1  |   """
bot_service_1  | 2021-10-07 22:52:57,239 - telegram.ext.dispatcher - ERROR - No error handlers are registe                                         red, logging exception.
bot_service_1  | Traceback (most recent call last):
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in                                          process_update
bot_service_1  |     handler.handle_update(update, self, check, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in han                                         dle_update
bot_service_1  |     return self.callback(update, context)
bot_service_1  |   File "bot.py", line 456, in getList
bot_service_1  |     user = update.message.from_user
bot_service_1  | AttributeError: 'NoneType' object has no attribute 'from_user'
bot_service_1  | 2021-10-07 22:53:22,118 - telegram.ext.dispatcher - ERROR - No error handlers are registe                                         red, logging exception.
bot_service_1  | Traceback (most recent call last):
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in                                          process_update
bot_service_1  |     handler.handle_update(update, self, check, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line                                          626, in handle_update
bot_service_1  |     new_state = handler.handle_update(update, dispatcher, check_result, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in han                                         dle_update
bot_service_1  |     return self.callback(update, context)
bot_service_1  |   File "bot.py", line 187, in checkCaptcha
bot_service_1  |     if CAPTCHA_DATA[user.id] != text:
bot_service_1  | KeyError: 65219073
bot_service_1  | 2021-10-07 22:53:40,720 - telegram.ext.dispatcher - ERROR - No error handlers are registe                                         red, logging exception.
bot_service_1  | Traceback (most recent call last):
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 555, in                                          process_update
bot_service_1  |     handler.handle_update(update, self, check, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/conversationhandler.py", line                                          626, in handle_update
bot_service_1  |     new_state = handler.handle_update(update, dispatcher, check_result, context)
bot_service_1  |   File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 198, in han                                         dle_update
bot_service_1  |     return self.callback(update, context)
bot_service_1  |   File "bot.py", line 187, in checkCaptcha
bot_service_1  |     if CAPTCHA_DATA[user.id] != text:
bot_service_1  | KeyError: 65219073
mongodb_1      |
mongodb_1      | WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
mongodb_1      |   see https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
mongodb_1      |   see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
mongodb_1      |
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.663+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.671+00:00"},"s":"W",  "c":"ASIO",     "id":22601,   "ctx":"main","msg":"No TransportLayer configured during NetworkInterface startup"}
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.671+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.672+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"4b3c32ff0e8c"}}
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.672+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.8","gitVersion":"83b8bb8b6b325d8d8d3dfd2ad9f744bdad7d6ca0","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.672+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
mongodb_1      | {"t":{"$date":"2021-10-07T22:52:09.672+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command

**Comment by trizin** [comment]
Try to change the MongoDB version. You can take a look at the other versions [on docker hub.](https://hub.docker.com/_/mongo?tab=tags)
